services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/abdelrhman06/n8n
    plan: free
    envVars:
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        value: ${DB_POSTGRESDB_HOST}

      - key: DB_POSTGRESDB_PORT
        value: ${DB_POSTGRESDB_PORT}

      - key: DB_POSTGRESDB_DATABASE
        value: ${DB_POSTGRESDB_DATABASE}

      - key: DB_POSTGRESDB_USER
        value: ${DB_POSTGRESDB_USER}

      - key: DB_POSTGRESDB_PASSWORD
        value: ${DB_POSTGRESDB_PASSWORD}

      - key: DB_POSTGRESDB_SSL
        value: "true"

      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"

      - key: N8N_BASIC_AUTH_USER
        value: ${N8N_BASIC_AUTH_USER}

      - key: N8N_BASIC_AUTH_PASSWORD
        value: ${N8N_BASIC_AUTH_PASSWORD}

      - key: WEBHOOK_URL
        value: ${WEBHOOK_URL}

      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      - key: N8N_RUNNERS_ENABLED
        value: "true"
